apiVersion: v1
kind: Secret
metadata:
  name: {{ include "accountabilidash.fullname" . }}-backend
  labels:
    {{- include "accountabilidash.backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  secret-key: {{ .Values.backend.secretKey | default (randAlphaNum 32) | quote }}
