{{- if .Values.postgres.useCloudNativePG }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "accountabilidash.fullname" . }}-postgres
  labels:
    {{- include "accountabilidash.postgres.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.postgres.auth.username | quote }}
  password: {{ .Values.postgres.auth.password | quote }}
  postgres-password: {{ .Values.postgres.auth.password | quote }}
{{- end }}
