{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "accountabilidash.fullname" . }}-postgres-config
  labels:
    {{- include "accountabilidash.postgres.labels" . | nindent 4 }}
data:
  postgres-user: {{ .Values.postgres.auth.username | quote }}
  postgres-db: {{ .Values.postgres.auth.database | quote }}
{{- end }}
