{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "accountabilidash.fullname" . }}-postgres
  labels:
    {{- include "accountabilidash.postgres.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.postgres.auth.password | quote }}
{{- end }}
